{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $tlsSecret := include "app.ingressSecret" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . | quote }}
    {{- end }}
  routes: |-
  {{- range .Values.ingressRoute.routes }}
    - match: {{ .rule | quote }}
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
  {{- end }}
  {{- if .Values.ingressRoute.tlsEnabled }}
  {{- with .Values.ingressRoute.tls }}
  tls:
    secretName: {{ $tlsSecret }}
    options: 
      {{- toYaml .options | nindent 6 }}
    certResolver: {{ .certResolver | quote }}
    domains:
      {{- range .domains }}
      - main: {{ .main | quote }}
        sans: |-
          {{- range .sans }}
          - {{ . | quote }}
          {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
