{{- if .Values.ingressRoute.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "app.imagePullSecret" . }}
{{- end }}
